### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by JonatanGust** [feffes/verifyIT#3]
java -jar target/verifyIT-1.0-SNAPSHOT-jar-with-dependencies.jar C:\Users\jonatan\Downloads\Report_20180425_2156.xls.xlsx C:\Users\jonatan\Desktop\Verifikat
110
2500
2500
470
540
40000
Exception in thread "main" java.lang.NumberFormatException: For input string: "151.59"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at main.kotlin.MainKt.main(Main.kt:68)

**Comment by JonatanGust** [comment]
SOLUTION:
1) Download file from GTT
2) change file ending from xls to csv
3) use reliable converter to xlsx
4) script now worked, (I used verifyit.jar from feffe.moe/dwnld/something)


Problem solved by not using google to "convert" to xlsx, it was giving "." instead of "," and it was actually a tsv file. Using https://www.coolutils.com/online/TSV-to-XLS# on the file from GTT (after changing from xls to csv) made the script working. Also note that the .jar used wasnt from this repo but fetched from feffe.moe, but the command was the same (xlsx in .jar folder with target dir also in the same folder)

**Comment by JonatanGust** [comment]
Seems I forgot the part where the conversion added a top row numbering columns, this does also mess with the program. (just remove it and shift every thing 1 row up)

**Comment by ericlp** [comment]
I had the same problem with "," and ".". I have also discovered that if your drive defaults to Swedish it will convert your .xlsx with "dots". But with drive defaulting to English it will convert to .xlsx with "commas".
